FROM node:12
COPY nodeapp /nodeapp
WORKDIR /nodeapp

ARG RDS_HOSTNAME="$RDS_HOSTNAME"
ARG RDS_USERNAME="$RDS_USERNAME"
ARG RDS_PASSWORD="$RDS_PASSWORD"
ARG RDS_PORT="$RDS_PORT"
ARG REDIS_HOSTNAME="$REDIS_HOSTNAME"
ARG REDIS_PORT="$REDIS_PORT"

RUN npm install
CMD ["node", "/nodeapp/app.js"]