apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: application
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: 10.96.0.18:8082/nodejs
        ports:
        - containerPort: 3000
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password  
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-database

      imagePullSecrets:
      - name: nexus-docker