apiVersion: "v1"
kind: "Service"
metadata:
  name: "application-deployment-service"
  namespace: "dev"
  labels:
    app: "application"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
    nodePort: 30030
  selector:
    app: "application"
  type: "NodePort"