apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: application
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: 10.97.253.249:8082/nodejs:4
        ports:
        - containerPort: 3000