pipeline {
    agent any
    
    stages {
        stage('Cloning our Git') {
            steps {
                 git branch: 'k8s_task', url: 'https://github.com/mustafaabdelbadea/jenkins_nodejs_example'
            }
        }   

        stage('Build image') {
            steps {
                sh 'docker build  --no-cache -t 10.96.0.18:8082/nodejs  .  '
            }
        }
         
        stage('Push image') {
            steps {
                  withCredentials([usernamePassword(credentialsId: 'nexus', passwordVariable: 'MYPASS', usernameVariable: 'MYUSER')]) {
                        sh "echo ${MYPASS} | docker login -u ${MYUSER} --password-stdin 10.96.0.18:8082"
                        sh 'docker push 10.96.0.18:8082/nodejs'
                    }
            }
        }

        stage('Delete local image') {
            steps {
                sh 'docker rmi 10.96.0.18:8082/nodejs'
            }
        }

        stage('Nexus logout') {
            steps {
                    sh "docker logout  10.96.0.18:8082"
            }
        }
      
    }
}
