pipeline {
    agent any
    
    stages {
        stage('Cloning our Git') {
            steps {
                 git branch: 'k8s_task', url: 'https://github.com/mustafaabdelbadea/jenkins_nodejs_example'
            }
        }   

        stage('Create pods') {
            steps {
                  withCredentials([usernamePassword(credentialsId: 'nexus', passwordVariable: 'MYPASS', usernameVariable: 'MYUSER')]) {
                        sh "echo ${MYPASS} | docker login -u ${MYUSER} --password-stdin 10.96.0.18:8082"
                        sh "chmod 555 ./k8s.sh"
                        sh './k8s.sh'

                    }
            }
        }

        stage('Nexus logout') {
            steps {
                    sh "docker logout  10.96.0.18:8082"
            }
        }
      
    }
}
